version: '3.9'
services:
  db:
    container_name: db
    image: mysql:8.1
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  nextjs:
    container_name: nextjs
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: nextjs.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
volumes:
  db:
    driver: local
networks:
  backend:
    driver: bridge
